# Generated by Django 4.2.6 on 2023-10-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_upload_alter_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.CharField(default='Your Default Value Here', max_length=122),
        ),
    ]
