# Generated by Django 4.2.6 on 2023-10-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_upload_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='type',
            new_name='type1',
        ),
    ]
