# Generated by Django 4.2.6 on 2023-10-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_type_upload_type1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.TextField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='photo',
            field=models.ImageField(upload_to=None),
        ),
    ]
