# Generated by Django 4.2.6 on 2023-10-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_upload_id_alter_upload_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
