# Generated by Django 4.2.6 on 2023-10-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_upload_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.CharField(max_length=1000000000000000000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
